'use strict';
const DashboardPage=(()=>{
 function render(){const u=Auth.getCurrent(),n=_esc((u?.fullName||u?.username||'مستخدم').split(/\s+/).slice(0,2).join(' ')),d=new Intl.DateTimeFormat('ar-EG',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());return `<div class="page active" id="page-dashboard"><div class="ops-hero"><div><div class="page-kicker">مركز العمليات</div><h2>مرحباً، ${n}</h2><p>${d} — ملخص الوردية وحالة المخزون.</p></div><div class="ops-health">النظام يعمل بصورة طبيعية</div></div><div id="dashContent"><div class="metric-grid">${Array(4).fill('<div class="metric-card"><div class="skeleton" style="height:76px"></div></div>').join('')}</div></div></div>`}
 async function afterRender(){try{const [s,m,t,a,l,e]=await Promise.all([DB.getStats(),DB.getMonthlySales(),DB.getTopMeds(),DB.getRecentActivity(),DB.getLowStock(),DB.getExpiring()]);draw(s,m,t,a,l,e)}catch(e){document.getElementById('dashContent').innerHTML=`<div class="alert err">تعذر تحميل لوحة العمليات: ${_esc(e.message)}</div>`}}
 function metric(icon,label,value,tag,color,bg){return `<article class="metric-card" style="--metric:${color};--metric-bg:${bg}"><div class="metric-top"><span class="metric-icon"><i class="fas ${icon}"></i></span><span class="metric-tag">${tag}</span></div><div class="metric-value">${value}</div><div class="metric-label">${label}</div></article>`}
 function draw(s,monthly,top,activity,low,expiring){const alerts=[...low.slice(0,3).map(m=>({i:'fa-box-open',c:'warn',n:m.name,d:`متبقي ${m.stock} — حد الطلب ${m.minStock}`,t:'مخزون منخفض'})),...expiring.slice(0,3).map(m=>({i:'fa-calendar-xmark',c:'err',n:m.name,d:`تنتهي في ${m.expiry}`,t:'صلاحية قريبة'}))].slice(0,5);document.getElementById('dashContent').innerHTML=`
 <div class="metric-grid">${metric('fa-cash-register','مبيعات اليوم',Fmt.money(s.todayRevenue),`${s.todayCount} فاتورة`,'#0f766e','#f0fbf9')}${metric('fa-chart-line','إيرادات الشهر',Fmt.money(s.monthRevenue),'الشهر الحالي','#2563a8','#eef5fd')}${metric('fa-boxes-stacked','الأصناف النشطة',Fmt.num(s.totalMeds),`${s.outOfStock||0} نافد`,'#6b57b6','#f3f0fc')}${metric('fa-triangle-exclamation','تحتاج متابعة',Fmt.num((s.lowStock||0)+(s.expiring||0)),'مخزون وصلاحية','#ba6b0b','#fff5e5')}</div>
 <div class="card" style="margin-bottom:.8rem"><div class="card-head"><span class="card-title"><i class="fas fa-bolt"></i> اختصارات الوردية</span></div><div class="card-body"><div class="action-list"><button class="action-tile" onclick="App.navigate('sales')"><i class="fas fa-cart-plus"></i><span><strong>فاتورة بيع</strong><small>ابدأ عملية بيع جديدة</small></span></button><button class="action-tile" onclick="App.navigate('medicines');setTimeout(()=>MedicinesPage.openAddModal(),250)"><i class="fas fa-capsules"></i><span><strong>إضافة صنف</strong><small>دواء أو منتج جديد</small></span></button><button class="action-tile" onclick="App.navigate('invoices')"><i class="fas fa-receipt"></i><span><strong>سجل الفواتير</strong><small>مراجعة أو طباعة</small></span></button><button class="action-tile" onclick="App.navigate('reports')"><i class="fas fa-chart-column"></i><span><strong>تقرير الوردية</strong><small>المبيعات والأرباح</small></span></button></div></div></div>
 <div class="dashboard-grid"><div class="card"><div class="card-head"><span class="card-title"><i class="fas fa-chart-simple"></i> اتجاه المبيعات خلال السنة</span><span class="badge bdg-teal">${new Date().getFullYear()}</span></div><div class="card-body"><div class="bar-chart tall" id="dashMonthly"></div></div></div><div class="card"><div class="card-head"><span class="card-title"><i class="fas fa-bell"></i> تحتاج تدخل الآن</span><button class="btn btn-ghost btn-sm" onclick="App.navigate('medicines')">المخزون</button></div><div class="card-body">${alerts.length?`<div class="attention-list">${alerts.map(x=>`<div class="attention-row"><span class="attention-icon" style="background:var(--${x.c}-light);color:var(--${x.c})"><i class="fas ${x.i}"></i></span><div><strong>${_esc(x.n)}</strong><small>${_esc(x.d)}</small></div><span class="badge ${x.c==='err'?'bdg-err':'bdg-warn'}">${x.t}</span></div>`).join('')}</div>`:'<div class="empty-state" style="padding:2rem"><div class="es-icon"><i class="fas fa-circle-check"></i></div><h3 class="es-title">المخزون مستقر</h3></div>'}</div></div></div>
 <div class="dashboard-grid"><div class="card"><div class="card-head"><span class="card-title"><i class="fas fa-ranking-star"></i> الأصناف الأكثر حركة</span></div><div class="card-body p0"><table class="dtable"><thead><tr><th>الصنف</th><th>الكمية</th><th>الإيراد</th></tr></thead><tbody>${top.length?top.map(m=>`<tr><td><strong>${_esc(m.name)}</strong></td><td>${Fmt.num(m.qty)}</td><td>${Fmt.money(m.revenue)}</td></tr>`).join(''):'<tr><td colspan="3" class="text-center text-muted">لا توجد مبيعات</td></tr>'}</tbody></table></div></div><div class="card"><div class="card-head"><span class="card-title"><i class="fas fa-clock-rotate-left"></i> آخر العمليات</span></div><div class="card-body">${activity.length?activity.slice(0,5).map(x=>`<div class="attention-row"><span class="attention-icon" style="background:var(--teal-50);color:var(--teal-600)"><i class="fas ${x.icon}"></i></span><div><strong>${_esc(x.title)}</strong><small>${_esc(x.desc)}</small></div><span class="text-xs text-muted">${x.time}</span></div>`).join(''):'<p class="text-center text-muted">لا توجد عمليات حديثة</p>'}</div></div></div>`;requestAnimationFrame(()=>renderBarChart('dashMonthly',monthly.labels.map(x=>x.slice(0,3)),monthly.values,'linear-gradient(180deg,#2fb3a7,#0f766e)'))}
 return{render,afterRender}
})();
